### ISSUE TITLE
Peer -to-peer code review. Friday 10/14/2022.

### ISSUE THREAD

**Issue by johnkioko** [AbayomiOlaoye/to-do_app#7]
Good job @AbayomiOlaoye 👏 . You have followed best practices and your code is DRY. Just a slight improvement I think you need to make on the below piece of your code.

[Click here to see the code snippet](https://github.com/AbayomiOlaoye/to-do_app/commit/64ff13aa09194d292926635696baa2fe6a9b148e#:~:text=for%20(let%20i%20%3D%20toDoList.tasks.length%20%2D%201%3B%20i%20%3E%3D%200%3B%20i%20%2D%3D%201))

**Comment by AbayomiOlaoye** [comment]
Thank you so much for your time, @johnkioko
